{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "compose-compiler-gradle-plugin",
    "version": "2.2.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-sources.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-sources.jar",
          "size": 12969,
          "sha512": "5642d657732a6545e5af15f14c31e6f7e7bfec9a32b8bce9f19c834aa6b4e9658230f8e648a6a41cf5054e9be5a960cb979959c4e975f14a7c2d6e48d033e7cd",
          "sha256": "bc7cd8c91c2b96e61ea2e59edb0c16ef78702c5681b5b3c857001f5717ae1aed",
          "sha1": "9df1c5dd3d7f97f180dc9851ac618b8f1108cad4",
          "md5": "4e1978c950d6e497c428990193e43aed"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-javadoc.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-javadoc.jar",
          "size": 311753,
          "sha512": "bf5a92624ff1e15ff5b7c2d5045f29024895498306ed1241fdc9316f22a3514007b1d2be2a41fdd640f63286b3f6d21f712577b5ee4cef7dd4eae65ed87b8fbb",
          "sha256": "95be91490cac4e4b4fb228e6838d17ec7b48799349a6d3c362ae940e25c3d11f",
          "sha1": "ae1b3337aa902fd86f05ac47f1a525ee29265df1",
          "md5": "9ba63f40320537e37ecddf10ec4f3bf3"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ]
    },
    {
      "name": "gradle80JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle80-javadoc.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle80-javadoc.jar",
          "size": 311818,
          "sha512": "4503ff9e5a3d79f1a53fadd084bef63863c1ee86fcf7417bebc37c5403d8408780e8011d4e19f78429046560217d7400aa28548c7e80b1fc83e4ae6aea7ff7ef",
          "sha256": "e3eb0c1fcd83ed8310d4d47cf1960006c2c6e265c7aa0fb5b28a4b8cf98b5e2f",
          "sha1": "e7507f86306dbbe11dd0f1bba947cb96170a319d",
          "md5": "3bee920843647b295db9605d46219afb"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle80SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle80-sources.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle80-sources.jar",
          "size": 12969,
          "sha512": "5642d657732a6545e5af15f14c31e6f7e7bfec9a32b8bce9f19c834aa6b4e9658230f8e648a6a41cf5054e9be5a960cb979959c4e975f14a7c2d6e48d033e7cd",
          "sha256": "bc7cd8c91c2b96e61ea2e59edb0c16ef78702c5681b5b3c857001f5717ae1aed",
          "sha1": "9df1c5dd3d7f97f180dc9851ac618b8f1108cad4",
          "md5": "4e1978c950d6e497c428990193e43aed"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle80ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle80.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle80.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle80RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle80.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle80.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle81JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle81-javadoc.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle81-javadoc.jar",
          "size": 311841,
          "sha512": "0e63bfb7aa8f3cad5ac675c9461cd87b1217564d7c38541851a9505f025afd2595e92fdeadbabeef9c6a2413788a39326ad01c2cc44e91f4cfaf4aa0c27ba1bf",
          "sha256": "f710ba36b42e654d1bb24bbf93044c4213446cce2cd9e125e77d5ebb4c786f01",
          "sha1": "383eb1654e1ee38615f81aac128059df50d05d97",
          "md5": "f44adf0cc842fe6bcac403da66237d2c"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle81SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle81-sources.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle81-sources.jar",
          "size": 12969,
          "sha512": "5642d657732a6545e5af15f14c31e6f7e7bfec9a32b8bce9f19c834aa6b4e9658230f8e648a6a41cf5054e9be5a960cb979959c4e975f14a7c2d6e48d033e7cd",
          "sha256": "bc7cd8c91c2b96e61ea2e59edb0c16ef78702c5681b5b3c857001f5717ae1aed",
          "sha1": "9df1c5dd3d7f97f180dc9851ac618b8f1108cad4",
          "md5": "4e1978c950d6e497c428990193e43aed"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle81ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle81.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle81.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle81RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle81.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle81.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle82JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle82-javadoc.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle82-javadoc.jar",
          "size": 311833,
          "sha512": "b160b348c3948a91e3701849ee5f7024ebb01df1e1519801cd53f58b11db8ab8d75fc8da0b3c7417056b094cfd41cdae5b49fb84f99627589c9167c6cc16ba37",
          "sha256": "49bb6f3494b7897a679a6eee3144d1f6a6ad760d4c4b4536e341dc0802c57a1f",
          "sha1": "29cffc61f27fb5614295c3a92fe7ad5373a250ec",
          "md5": "e423f15f12630319b5ccd99ea469e271"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle82SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle82-sources.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle82-sources.jar",
          "size": 12969,
          "sha512": "5642d657732a6545e5af15f14c31e6f7e7bfec9a32b8bce9f19c834aa6b4e9658230f8e648a6a41cf5054e9be5a960cb979959c4e975f14a7c2d6e48d033e7cd",
          "sha256": "bc7cd8c91c2b96e61ea2e59edb0c16ef78702c5681b5b3c857001f5717ae1aed",
          "sha1": "9df1c5dd3d7f97f180dc9851ac618b8f1108cad4",
          "md5": "4e1978c950d6e497c428990193e43aed"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle82ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle82.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle82.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle82RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle82.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle82.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle85JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle85-javadoc.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle85-javadoc.jar",
          "size": 311831,
          "sha512": "f1a7aa3f71270e35c6287a2f98362b8681c8c1e2f8bb39f3627c0861cebf79e51c6d6464198b949695f1d6992055ec32a78104c20e40df4fe4291b685dea35ec",
          "sha256": "3f9e4cdd4627a9715477bf9e2700cfc0726cb8b979465ba5213af744b6543c1b",
          "sha1": "bdef18b68b5281e4a0ffb7aec55e3541cbf12b26",
          "md5": "cf1836fa29e87ae3196efc52170ba92a"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle85SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle85-sources.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle85-sources.jar",
          "size": 12969,
          "sha512": "5642d657732a6545e5af15f14c31e6f7e7bfec9a32b8bce9f19c834aa6b4e9658230f8e648a6a41cf5054e9be5a960cb979959c4e975f14a7c2d6e48d033e7cd",
          "sha256": "bc7cd8c91c2b96e61ea2e59edb0c16ef78702c5681b5b3c857001f5717ae1aed",
          "sha1": "9df1c5dd3d7f97f180dc9851ac618b8f1108cad4",
          "md5": "4e1978c950d6e497c428990193e43aed"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle85ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle85.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle85.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle85RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle85.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle85.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle86JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle86-javadoc.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle86-javadoc.jar",
          "size": 311846,
          "sha512": "b290bacd5e4b9a1a26d6c9aaeaa439aaa4cbfeefc54a831db875db89cb4ed1a257dc1186bf98d53738fdd3674358b54c6372e52b168e2839d848b3f5d636a356",
          "sha256": "914b9fa0edeefe410fbee071f2318c56c115a515927c41b133f9010c24b57c5a",
          "sha1": "15a1edcfa901adfda73ac39d32fc4250e92de615",
          "md5": "b3ca26c911cbcea239ce74885d44e902"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle86SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle86-sources.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle86-sources.jar",
          "size": 12969,
          "sha512": "5642d657732a6545e5af15f14c31e6f7e7bfec9a32b8bce9f19c834aa6b4e9658230f8e648a6a41cf5054e9be5a960cb979959c4e975f14a7c2d6e48d033e7cd",
          "sha256": "bc7cd8c91c2b96e61ea2e59edb0c16ef78702c5681b5b3c857001f5717ae1aed",
          "sha1": "9df1c5dd3d7f97f180dc9851ac618b8f1108cad4",
          "md5": "4e1978c950d6e497c428990193e43aed"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle86ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle86"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle86.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle86.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle86RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle86"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle86.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle86.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle88JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle88-javadoc.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle88-javadoc.jar",
          "size": 311826,
          "sha512": "2fa46f39e87d0ac8016b6aa6eba7c86b8ba5c4c422d8b555d6206a7be8eee4716188b82ca9132101a4fc67cebd04b61356c9bd4381bbf761f95d298b824adf26",
          "sha256": "5e77169bcaea564e8a9f33fa5d9e8721afb3a974e59458571ebab49d09016de2",
          "sha1": "76ee9e45b98871e4adea2a67cdeda9c7ec7742af",
          "md5": "bc2abe4922f26a3992659bf5551715ba"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle88SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle88-sources.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle88-sources.jar",
          "size": 12969,
          "sha512": "5642d657732a6545e5af15f14c31e6f7e7bfec9a32b8bce9f19c834aa6b4e9658230f8e648a6a41cf5054e9be5a960cb979959c4e975f14a7c2d6e48d033e7cd",
          "sha256": "bc7cd8c91c2b96e61ea2e59edb0c16ef78702c5681b5b3c857001f5717ae1aed",
          "sha1": "9df1c5dd3d7f97f180dc9851ac618b8f1108cad4",
          "md5": "4e1978c950d6e497c428990193e43aed"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle88ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle88"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle88.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle88.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle88RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle88"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle88.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle88.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle811JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle811-javadoc.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle811-javadoc.jar",
          "size": 311885,
          "sha512": "ed219450182519dcbe26cdc6120d3425bc567e16e51720861fdbdd71d702a853886e498fe11889fd5254a9ce286bd6f2e4b93abf304d1097cf4df839fb98bb89",
          "sha256": "be9f2f8664c6023f8025721f29e9e30ce988e4e53f0aacdbfff64f1c49550d7b",
          "sha1": "2a37c0ec5a8d6d63a0c732011ab6fcfebe96d771",
          "md5": "d560c753b9e355ddb776c6d916d170f5"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle811SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle811-sources.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle811-sources.jar",
          "size": 12969,
          "sha512": "5642d657732a6545e5af15f14c31e6f7e7bfec9a32b8bce9f19c834aa6b4e9658230f8e648a6a41cf5054e9be5a960cb979959c4e975f14a7c2d6e48d033e7cd",
          "sha256": "bc7cd8c91c2b96e61ea2e59edb0c16ef78702c5681b5b3c857001f5717ae1aed",
          "sha1": "9df1c5dd3d7f97f180dc9851ac618b8f1108cad4",
          "md5": "4e1978c950d6e497c428990193e43aed"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle811ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle811"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle811.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle811.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle811RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle811"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle811.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle811.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle813JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle813-javadoc.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle813-javadoc.jar",
          "size": 311855,
          "sha512": "d39918a8297052b77a01014dfcc7497e2bb48e164d683f6500a77448b6224aed083bdebc5fdeebb1860271819316d53b4187e51cb8d4b165b38913d8770a6c64",
          "sha256": "6f05c1cf9eae6224d4b0187c567ebf8553d73015d9814bf2b7bb5a4aa2323a8c",
          "sha1": "a0b0162e46116b4dfb21f9b4a77a542e31c0f468",
          "md5": "82d4abf67b361fe863f89e88b4fc60d1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle813SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle813-sources.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle813-sources.jar",
          "size": 12969,
          "sha512": "5642d657732a6545e5af15f14c31e6f7e7bfec9a32b8bce9f19c834aa6b4e9658230f8e648a6a41cf5054e9be5a960cb979959c4e975f14a7c2d6e48d033e7cd",
          "sha256": "bc7cd8c91c2b96e61ea2e59edb0c16ef78702c5681b5b3c857001f5717ae1aed",
          "sha1": "9df1c5dd3d7f97f180dc9851ac618b8f1108cad4",
          "md5": "4e1978c950d6e497c428990193e43aed"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle813ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle813"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle813.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle813.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    },
    {
      "name": "gradle813RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-model",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle813"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-compiler-gradle-plugin-2.2.20-gradle813.jar",
          "url": "compose-compiler-gradle-plugin-2.2.20-gradle813.jar",
          "size": 50146,
          "sha512": "113081b7d018283b845d5bfbffdd9cefb81db69ac7925342f2c8898274f96d6b1f948c85160c6973e285b0b775c6bda512c91bfbca01f3f8bad1f60421a22dad",
          "sha256": "a3385b8a94cf4f00957ea7da0e25ea93053c1acc648e45df168b3d83ffc2d473",
          "sha1": "f3df90c90819856479691e3a513c71d6d1ebc6ba",
          "md5": "af9353f0cc6ceb2de0f165a61ac147b0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "compose-compiler-gradle-plugin",
          "version": "2.2.20"
        }
      ]
    }
  ]
}
